/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.component;
import dao.KategoriDAO;
import dao.ProdukDAO;
import dao.SupplierDAO;
import java.util.List;
import javax.swing.JOptionPane;
import model.Kategori;
import model.Produk;
import model.Supplier;
/**
 *
 * @author M Rizky Khatami
 */
public class InputProdukForm extends javax.swing.JDialog {
    
    private final KategoriDAO kategoriDAO = new KategoriDAO();
    private final SupplierDAO supplierDAO = new SupplierDAO();
    private final ProdukDAO produkDAO = new ProdukDAO();

    private List<Kategori> listKategori;
    private List<Supplier> listSupplier;
    
    private Produk editingProduk;   // null = tambah, != null = edit
    private boolean saved = false;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InputProdukForm.class.getName());

    /**
     * Creates new form TambahProdukForm
     */
        // Konstruktor untuk TAMBAH
    public InputProdukForm(java.awt.Frame parent, boolean modal) {
        this(parent, modal, null);
    }

    // 2. Ubah Window menjadi java.awt.Frame
    public InputProdukForm(java.awt.Frame parent, boolean modal, Produk produkToEdit) {
        super(parent, modal); // JDialog membutuhkan (Frame, boolean)
        initComponents();
        
        this.editingProduk = produkToEdit; // Set variabel dulu
        
        loadComboBoxData();
        setupMode(); // Baru jalankan setup mode
        
        setLocationRelativeTo(parent); // Posisi di tengah parent
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tambahButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        namaProdukField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        hargaField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        kategoriComboBox = new javax.swing.JComboBox<>();
        stokSpinner = new javax.swing.JSpinner();
        supplierComboBox = new javax.swing.JComboBox<>();
        batalButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tambahButton.setText("TAMBAH");
        tambahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Nama Produk");

        jLabel4.setText("Kategori");

        jLabel5.setText("Harga");

        jLabel6.setText("Stok");

        jLabel7.setText("Supplier");

        kategoriComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        stokSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        supplierComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        batalButton.setText("BATAL");
        batalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tambahButton))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(namaProdukField)
                            .addComponent(hargaField)
                            .addComponent(kategoriComboBox, 0, 280, Short.MAX_VALUE)
                            .addComponent(stokSpinner)
                            .addComponent(supplierComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(batalButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaProdukField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kategoriComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hargaField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stokSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supplierComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tambahButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(batalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("INPUT PRODUK");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void batalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalButtonActionPerformed
        dispose();
    }//GEN-LAST:event_batalButtonActionPerformed

    private void tambahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahButtonActionPerformed
        String namaProduk = namaProdukField.getText().trim();
        String hargaText = hargaField.getText().trim();
        int stok = (Integer) stokSpinner.getValue();

        int indexKategori = kategoriComboBox.getSelectedIndex();
        int indexSupplier = supplierComboBox.getSelectedIndex();

        if (namaProduk.isEmpty() || hargaText.isEmpty()
                || indexKategori < 0 || indexSupplier < 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Semua field wajib diisi!",
                    "Peringatan",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int harga;
        try {
            harga = Integer.parseInt(hargaText);
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Harga harus berupa angka!",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (harga < 1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Harga minimal RP 1!",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (stok < 0) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Stok tidak boleh kurang dari 0!",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Kategori kategoriTerpilih = listKategori.get(indexKategori);
        Supplier supplierTerpilih = listSupplier.get(indexSupplier);

        try {
            if (editingProduk == null) {
                // MODE TAMBAH
                Produk p = new Produk();
                p.setNamaProduk(namaProduk);
                p.setHarga(harga);
                p.setStok(stok);
                p.setIdKategori(kategoriTerpilih.getIdKategori());
                p.setIdSupplier(supplierTerpilih.getIdSupplier());

                produkDAO.addProduk(p);
            } else {
                // MODE EDIT
                editingProduk.setNamaProduk(namaProduk);
                editingProduk.setHarga(harga);
                editingProduk.setStok(stok);
                editingProduk.setIdKategori(kategoriTerpilih.getIdKategori());
                editingProduk.setIdSupplier(supplierTerpilih.getIdSupplier());

                produkDAO.updateProduk(editingProduk);
            }

            saved = true;
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Data produk berhasil disimpan!",
                    "Informasi",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
            dispose();

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Gagal menyimpan produk: " + ex.getMessage(),
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tambahButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                InputProdukForm dialog = new InputProdukForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batalButton;
    private javax.swing.JTextField hargaField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> kategoriComboBox;
    private javax.swing.JTextField namaProdukField;
    private javax.swing.JSpinner stokSpinner;
    private javax.swing.JComboBox<String> supplierComboBox;
    private javax.swing.JButton tambahButton;
    // End of variables declaration//GEN-END:variables

    private void loadComboBoxData() {
        // Load kategori
        listKategori = kategoriDAO.getAllKategori();
        kategoriComboBox.removeAllItems();
        for (Kategori k : listKategori) {
            kategoriComboBox.addItem(k.getNamaKategori());
        }

        // Load supplier
        listSupplier = supplierDAO.getAllSupplier();
        supplierComboBox.removeAllItems();
        for (Supplier s : listSupplier) {
            supplierComboBox.addItem(s.getNamaSupplier());
        }
    }
    
    public boolean isSaved() {
        return saved;
    }
    
        private void setupMode() {
        if (editingProduk == null) {
            // Mode TAMBAH
            jLabel2.setText("TAMBAH PRODUK");
            tambahButton.setText("TAMBAH");
        } else {
            // Mode EDIT
            jLabel2.setText("PERBARUI PRODUK");
            tambahButton.setText("SIMPAN");

            // Isi field
            namaProdukField.setText(editingProduk.getNamaProduk());
            hargaField.setText(String.valueOf(editingProduk.getHarga()));
            stokSpinner.setValue(editingProduk.getStok());

            // Pilih kategori di combobox
            int selectedIndexKategori = -1;
            for (int i = 0; i < listKategori.size(); i++) {
                if (listKategori.get(i).getIdKategori() == editingProduk.getIdKategori()) {
                    selectedIndexKategori = i;
                    break;
                }
            }
            if (selectedIndexKategori >= 0) {
                kategoriComboBox.setSelectedIndex(selectedIndexKategori);
            }

            // Pilih supplier di combobox
            int selectedIndexSupplier = -1;
            for (int i = 0; i < listSupplier.size(); i++) {
                if (listSupplier.get(i).getIdSupplier() == editingProduk.getIdSupplier()) {
                    selectedIndexSupplier = i;
                    break;
                }
            }
            if (selectedIndexSupplier >= 0) {
                supplierComboBox.setSelectedIndex(selectedIndexSupplier);
            }
        }
    }

}
