/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.component;

import dao.LaporanPembelianPenjualanDAO;
import dao.SupplierDAO;
import java.text.DecimalFormat;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import model.Pembelian;
import model.Penjualan;
import model.Supplier;
/**
 *
 * @author Personal
 */
public class LaporanPembelianPenjualanForm extends javax.swing.JPanel {

    private LaporanPembelianPenjualanDAO dao;
    private DefaultTableModel tableModel;
    private DecimalFormat df = new DecimalFormat("#,###");
    private String mode;
    private final SupplierDAO supplierDAO = new SupplierDAO();
    private List<Supplier> listSupplier;
    
    /**
     * Creates new form LaporanPenjualanForm
     */
    public LaporanPembelianPenjualanForm(String mode) {
        initComponents();
        this.mode = mode;
        panelLabel.setText("LAPORAN TRANSAKSI " + mode);
        dao = new LaporanPembelianPenjualanDAO();
        String[] judul;
        
        if(mode.equalsIgnoreCase("PENJUALAN")){
            judul = new String[] {"ID Transaksi", "Tanggal", "Kasir", "Total Penjualan"};
        } else {
            judul = new String[] {"ID Transaksi", "Tanggal", "Kasir", "Supplier","Total Belanja"};
        }
        
        tableModel = new DefaultTableModel(judul, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblLaporan.setModel(tableModel);
        listSupplier = supplierDAO.getAllSupplier();
        loadData();
    }
    
    private void loadData() {
        listSupplier = supplierDAO.getAllSupplier(); 

        tableModel.setRowCount(0); 
        if (mode.equalsIgnoreCase("PENJUALAN")){
            List<Penjualan> list = dao.getAllPenjualan();
        
            for (Penjualan p : list) {
                Object[] row = {
                    p.getIdPenjualan(),
                    p.getTanggal(),
                    p.getNamaUser(),
                    df.format(p.getTotalHarga())
                };
                tableModel.addRow(row);
            }
        } else {
            List<Pembelian> list = dao.getAllPembelian();
        
            for (Pembelian p : list) {
//                System.out.println("ID Transaksi: " + p.getIdPembelian() + " | ID Supplier: " + p.getIdSupplier());
                Object[] row = {
                    p.getIdPembelian(),
                    p.getTanggal(),
                    p.getNamaUser(),
                    getNamaSupplierById(p.getIdSupplier()), 
                    df.format(p.getTotalHarga())
                };
                tableModel.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLaporan = new javax.swing.JTable();
        btnDetail = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        panelLabel.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        panelLabel.setText("LAPORAN TRANSAKSI PENJUALAN");

        tblLaporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Transaksi", "Tanggal", "Kasir", "Total Belanja"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblLaporan);

        btnDetail.setText("LIHAT DETAIL");
        btnDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailActionPerformed(evt);
            }
        });

        btnRefresh.setText("REFRESH");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE)
                        .addGap(45, 45, 45))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDetail)
                        .addGap(18, 18, 18)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(panelLabel)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailActionPerformed
        int row = tblLaporan.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih transaksi yang ingin dilihat detailnya!");
            return;
        }
        
        String tanggalLengkap = tblLaporan.getValueAt(row, 1).toString();
        
        int idPembelianOrPenjualan = Integer.parseInt(tblLaporan.getValueAt(row, 0).toString());

        JFrame parent = (JFrame) SwingUtilities.getWindowAncestor(this);
        LaporanPembelianPenjualanDialog dialog = new LaporanPembelianPenjualanDialog(parent, true);
        dialog.tampilkanDetail(mode, idPembelianOrPenjualan, tanggalLengkap);
    }//GEN-LAST:event_btnDetailActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        loadData();
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetail;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel panelLabel;
    private javax.swing.JTable tblLaporan;
    // End of variables declaration//GEN-END:variables

    private String getNamaSupplierById(int idSupplier) {
        if (listSupplier == null || listSupplier.isEmpty()) {
            return "Unknown (List Empty)";
        }

        for (Supplier s : listSupplier) {
            if (s.getIdSupplier() == idSupplier) {
                return s.getNamaSupplier();
            }
        }
        return "Unknown";
    }

}
