/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.component;

import dao.PembelianDAO;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import model.DetailPembelian;
import model.Pembelian;
import model.Produk;
import model.User;

/**
 *
 * @author M Rizky Khatami
 */
public class PembelianForm extends javax.swing.JPanel {
    private PembelianDAO pembelianDAO;
    private List<DetailPembelian> keranjang;
    private DefaultTableModel tableModel;
    
    private User userLogin;
    private int idSupplierDipilih = 0;
    
    private DecimalFormat df = new DecimalFormat("#,###");
    /**
     * Creates new form PembelianForm
     */
    public PembelianForm(User user) {
        initComponents();
        
        pembelianDAO = new PembelianDAO();
        keranjang = new ArrayList<>();
        
        String[] judul = {"ID Produk", "Nama Produk", "Nama Supplier", "Harga Satuan", "Kuantitas", "Subtotal"};
        tableModel = new DefaultTableModel(judul, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblKeranjang.setModel(tableModel);
        
        lblTotal.setText("0");
        
        userLogin = user;
    }
    
    public void setUserLogin(User user) {
        this.userLogin = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKeranjang = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtIdProduk = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnCariProduk = new javax.swing.JButton();
        txtNamaProduk = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnHapusItem = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnBatal = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtNamaSupplier = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        btnBersihkan = new javax.swing.JButton();

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel3.setText("DATA PEMBELIAN");

        tblKeranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Produk", "Nama Produk", "Nama Supplier", "Harga Satuan", "Kuantitas", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblKeranjang);

        jLabel1.setText("ID Produk");

        txtIdProduk.setEditable(false);
        txtIdProduk.setRequestFocusEnabled(false);
        txtIdProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdProdukActionPerformed(evt);
            }
        });

        jLabel2.setText("Nama Produk ");

        btnCariProduk.setText("CARI PRODUK");
        btnCariProduk.setNextFocusableComponent(txtHarga);
        btnCariProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariProdukActionPerformed(evt);
            }
        });

        txtNamaProduk.setEditable(false);
        txtNamaProduk.setRequestFocusEnabled(false);

        btnTambah.setText("TAMBAH");
        btnTambah.setNextFocusableComponent(btnBersihkan);
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnHapusItem.setText("HAPUS ITEM");
        btnHapusItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusItemActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("TOTAL HARGA");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Rp");

        lblTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTotal.setText("total");

        btnBatal.setText("BATAL");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnSimpan.setText("SIMPAN");
        btnSimpan.setNextFocusableComponent(btnBatal);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        jLabel8.setText("Nama Supplier ");

        txtNamaSupplier.setEditable(false);
        txtNamaSupplier.setRequestFocusEnabled(false);

        jLabel9.setText("Harga Satuan");

        txtHarga.setNextFocusableComponent(txtJumlah);

        jLabel10.setText("Jumlah");

        txtJumlah.setNextFocusableComponent(btnTambah);

        btnBersihkan.setText("BERSIHKAN");
        btnBersihkan.setNextFocusableComponent(btnSimpan);
        btnBersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBersihkanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHapusItem))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel7)
                                .addGap(10, 10, 10)
                                .addComponent(lblTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCariProduk)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel8))
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtIdProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNamaProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNamaSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(90, 90, 90)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10)
                                            .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(22, 22, 22)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnBersihkan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 547, Short.MAX_VALUE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addGap(33, 33, 33)
                .addComponent(btnCariProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtIdProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNamaProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtNamaSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBersihkan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(btnHapusItem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(lblTotal)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariProdukActionPerformed
        JFrame parent = (JFrame) SwingUtilities.getWindowAncestor(this);
        PilihProdukDialog dialog = new PilihProdukDialog(parent, true, true); // true = mode pembelian
        dialog.setVisible(true);

        if (dialog.produkTerpilih != null) {
            Produk p = dialog.produkTerpilih;
            txtIdProduk.setText(String.valueOf(p.getIdProduk()));
            txtNamaProduk.setText(p.getNamaProduk());
            txtNamaSupplier.setText(p.getNamaSupplier());
            
            // Simpan ID supplier
            idSupplierDipilih = p.getIdSupplier();
            
            // Kosongkan field harga dan jumlah agar user mengisi manual
            txtHarga.setText("");
            txtJumlah.setText("");
            
            txtHarga.requestFocus();
        }
    }//GEN-LAST:event_btnCariProdukActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        if (txtIdProduk.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih produk terlebih dahulu!");
            return;
        }
        if (txtHarga.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan harga satuan!");
            return;
        }
        if (txtJumlah.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan jumlah!");
            return;
        }

        try {
            int id = Integer.parseInt(txtIdProduk.getText());
            String nama = txtNamaProduk.getText();
            String supplier = txtNamaSupplier.getText();
            int harga = Integer.parseInt(txtHarga.getText());
            int qty = Integer.parseInt(txtJumlah.getText());

            if (harga <= 0) {
                JOptionPane.showMessageDialog(this, "Harga harus lebih dari 0!");
                return;
            }
            if (qty <= 0) {
                JOptionPane.showMessageDialog(this, "Jumlah harus lebih dari 0!");
                return;
            }

            int subtotal = harga * qty;

            boolean ada = false;
            for(DetailPembelian d : keranjang) {
                if(d.getIdProduk() == id) {
                    d.setJumlah(d.getJumlah() + qty);
                    d.setSubTotal(d.getHargaSatuan() * d.getJumlah());
                    ada = true;
                    break;
                }
            }

            if(!ada) {
                DetailPembelian detail = new DetailPembelian(id, nama, supplier, qty, harga, subtotal);
                keranjang.add(detail);
            }

            updateTabel();
            bersihkanFieldProduk();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Format harga atau jumlah salah! Harus berupa angka.");
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnHapusItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusItemActionPerformed
        int row = tblKeranjang.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih item di keranjang yang akan dihapus!");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
            "Yakin ingin menghapus item ini dari keranjang?",
            "Konfirmasi Hapus",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);

        if (confirm == JOptionPane.YES_OPTION) {
            keranjang.remove(row);
            updateTabel();
        }
    }//GEN-LAST:event_btnHapusItemActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        if (keranjang.isEmpty()) {
            resetForm();
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this,
            "Yakin ingin membatalkan transaksi ini?\nSemua item di keranjang akan dihapus.",
            "Konfirmasi Batal",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);

        if (confirm == JOptionPane.YES_OPTION) {
            resetForm();
        }
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        if (keranjang.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Keranjang masih kosong!");
            return;
        }

        if (idSupplierDipilih == 0) {
            JOptionPane.showMessageDialog(this, "Supplier belum dipilih!");
            return;
        }

        int total = hitungTotalBelanja();

        int confirm = JOptionPane.showConfirmDialog(this,
            "Total Transaksi: Rp " + df.format(total) + "\nSimpan data pembelian ini?",
            "Konfirmasi",
            JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            Pembelian p = new Pembelian();

            if (userLogin != null) {
                p.setIdUser(userLogin.getIdUser());
            } else {
                p.setIdUser(1); // Default user ID
            }

            p.setIdSupplier(idSupplierDipilih);
            p.setTotalHarga(total);
            p.setListDetail(keranjang);

            boolean sukses = pembelianDAO.simpanTransaksi(p);

            if (sukses) {
                JOptionPane.showMessageDialog(this, "Transaksi Pembelian Berhasil Disimpan!");
                resetForm();
            } else {
                JOptionPane.showMessageDialog(this, "Transaksi Gagal! Silakan coba lagi.");
            }
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void txtIdProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdProdukActionPerformed

    private void btnBersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBersihkanActionPerformed
        bersihkanFieldProduk();
    }//GEN-LAST:event_btnBersihkanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnBersihkan;
    private javax.swing.JButton btnCariProduk;
    private javax.swing.JButton btnHapusItem;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblKeranjang;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtIdProduk;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtNamaProduk;
    private javax.swing.JTextField txtNamaSupplier;
    // End of variables declaration//GEN-END:variables
    private void resetForm() {
        bersihkanFieldProduk();
        lblTotal.setText("0");
        
        keranjang.clear();
        tableModel.setRowCount(0);
        
        idSupplierDipilih = 0;
    }
    
    
    private void bersihkanFieldProduk() {
        txtIdProduk.setText("");
        txtNamaProduk.setText("");
        txtNamaSupplier.setText("");
        txtHarga.setText("");
        txtJumlah.setText("");
    }
      
    private void updateTabel() {
        tableModel.setRowCount(0);
        int total = 0;
        
        for (DetailPembelian d : keranjang) {
            total += d.getSubTotal();
            Object[] row = {
                d.getIdProduk(),
                d.getNamaProduk(),
                d.getNamaSupplier(),
                df.format(d.getHargaSatuan()),
                d.getJumlah(),
                df.format(d.getSubTotal())
            };
            tableModel.addRow(row);
        }
        
        lblTotal.setText(df.format(total));
    }

    private int hitungTotalBelanja() {
        int total = 0;
        for (DetailPembelian d : keranjang) {
            total += d.getSubTotal();
        }
        return total;
    }
}
