/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.component;

import dao.PenjualanDAO;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import model.DetailPenjualan;
import model.Penjualan;
import model.Produk;
import model.User;
/**
 *
 * @author Personal
 */
public class PenjualanForm extends javax.swing.JPanel {

    private PenjualanDAO penjualanDAO;
    private List<DetailPenjualan> keranjang; // List sementara (Keranjang Belanja)
    private DefaultTableModel tableModel;
    
    private User userLogin;
    private int stokSaatIni = 0;
    
    // Format mata uang
    private DecimalFormat df = new DecimalFormat("#,###");
    
    /**
     * Creates new form PenjualanForm
     */
    public PenjualanForm(User user) {
        initComponents();
        
        this.userLogin = user;
        
        penjualanDAO = new PenjualanDAO();
        keranjang = new ArrayList<>();
        
        String[] judul = {"ID Produk", "Nama Produk", "Harga", "Kuantitas", "Subtotal"};
        tableModel = new DefaultTableModel(judul, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tblKeranjang.setModel(tableModel);
        
        resetForm();
    }

    private void resetForm() {
        txtIdProduk.setText("");
        txtNamaProduk.setText("");
        txtHarga.setText("");
        txtJumlah.setText("");
//        txtBayar.setText("");
//        txtKembalian.setText("");
        lblTotal.setText("0");
        stokSaatIni = 0;
        
        keranjang.clear();
        tableModel.setRowCount(0);
    }
    
    private void updateTabel() {
        tableModel.setRowCount(0);
        double total = 0;
        
        for (DetailPenjualan d : keranjang) {
            total += d.getSubtotal();
            Object[] row = {
                d.getIdProduk(),
                d.getNamaProduk(),
                df.format(d.getHargaSatuan()),
                d.getJumlah(),
                df.format(d.getSubtotal())
            };
            tableModel.addRow(row);
        }
        
        lblTotal.setText(df.format(total));
    }
    
    private int hitungTotalBelanja() {
        int total = 0;
        for (DetailPenjualan d : keranjang) {
            total += d.getSubtotal();
        }
        return total;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKeranjang = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtIdProduk = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNamaProduk = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        btnCariProduk = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnHapusItem = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnBatal = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel3.setText("DATA PENJUALAN");

        tblKeranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Produk", "Nama Produk", "Harga", "Kuantitas", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblKeranjang);

        jLabel1.setText("ID Produk ");

        txtIdProduk.setEditable(false);
        txtIdProduk.setRequestFocusEnabled(false);

        jLabel2.setText("Nama Produk");

        txtNamaProduk.setEditable(false);
        txtNamaProduk.setRequestFocusEnabled(false);
        txtNamaProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaProdukActionPerformed(evt);
            }
        });

        jLabel4.setText("Harga Produk");

        txtHarga.setEditable(false);
        txtHarga.setRequestFocusEnabled(false);
        txtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaActionPerformed(evt);
            }
        });

        btnCariProduk.setText("CARI PRODUK");
        btnCariProduk.setNextFocusableComponent(txtJumlah);
        btnCariProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariProdukActionPerformed(evt);
            }
        });

        jLabel5.setText("Jumlah ");

        txtJumlah.setNextFocusableComponent(btnTambah);
        txtJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahActionPerformed(evt);
            }
        });

        btnTambah.setText("TAMBAH");
        btnTambah.setNextFocusableComponent(btnSimpan);
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnHapusItem.setText("HAPUS ITEM");
        btnHapusItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusItemActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("TOTAL :");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Rp");

        lblTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTotal.setText("total");

        btnBatal.setText("BATAL");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnSimpan.setText("SIMPAN");
        btnSimpan.setNextFocusableComponent(btnBatal);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCariProduk)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNamaProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtIdProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(92, 92, 92)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 135, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnHapusItem))))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(20, 20, 20)
                                .addComponent(jLabel7)
                                .addGap(10, 10, 10)
                                .addComponent(lblTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addGap(33, 33, 33)
                .addComponent(btnCariProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIdProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNamaProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnHapusItem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(lblTotal)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariProdukActionPerformed
        JFrame parent = (JFrame) SwingUtilities.getWindowAncestor(this);
        PilihProdukDialog dialog = new PilihProdukDialog(parent, true);
        dialog.setVisible(true);
        
        if (dialog.produkTerpilih != null) {
            Produk p = dialog.produkTerpilih;
            txtIdProduk.setText(String.valueOf(p.getIdProduk()));
            txtNamaProduk.setText(p.getNamaProduk());
            txtHarga.setText(String.valueOf(p.getHarga()));
            
            stokSaatIni = p.getStok(); 
            
            txtJumlah.requestFocus();
        }
    }//GEN-LAST:event_btnCariProdukActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        if (txtIdProduk.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih produk dulu!");
            return;
        }
        if (txtJumlah.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan jumlah!");
            return;
        }
        
        try {
            int id = Integer.parseInt(txtIdProduk.getText());
            String nama = txtNamaProduk.getText();
            int harga = Integer.parseInt(txtHarga.getText());
            int qtyInput = Integer.parseInt(txtJumlah.getText());
            
            if (qtyInput <= 0) {
                JOptionPane.showMessageDialog(this, "Jumlah beli tidak boleh 0 atau kurang!");
                return;
            }

            int qtyDiKeranjang = 0;
            for (DetailPenjualan d : keranjang) {
                if (d.getIdProduk() == id) {
                    qtyDiKeranjang = d.getJumlah();
                    break;
                }
            }
            
            int totalAkanDibeli = qtyInput + qtyDiKeranjang;

            if (totalAkanDibeli > stokSaatIni) {
                JOptionPane.showMessageDialog(this, 
                    "Stok tidak mencukupi!\nStok Tersedia: " + stokSaatIni + 
                    "\nSudah di keranjang: " + qtyDiKeranjang);
                return;
            }
            
            int subtotal = harga * qtyInput;
            
            boolean ada = false;
            for(DetailPenjualan d : keranjang) {
                if(d.getIdProduk() == id) {
                    d.setJumlah(d.getJumlah() + qtyInput);
                    d.setSubtotal(d.getHargaSatuan() * d.getJumlah());
                    ada = true;
                    break;
                }
            }
            
            if(!ada) {
                DetailPenjualan detail = new DetailPenjualan(id, nama, qtyInput, harga, subtotal);
                keranjang.add(detail);
            }
            
            updateTabel();
            
            txtIdProduk.setText("");
            txtNamaProduk.setText("");
            txtHarga.setText("");
            txtJumlah.setText("");
            stokSaatIni = 0;
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Format jumlah harus berupa angka!");
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnHapusItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusItemActionPerformed
        int row = tblKeranjang.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih item di keranjang yang akan dihapus!");
            return;
        }
        
        keranjang.remove(row);
        updateTabel();
    }//GEN-LAST:event_btnHapusItemActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        if (keranjang.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Keranjang masih kosong!");
            return;
        }
        
        int total = hitungTotalBelanja();
        
        int confirm = JOptionPane.showConfirmDialog(this, 
                "Total Transaksi: Rp " + df.format(total) + "\nSimpan data ini?", 
                "Konfirmasi", 
                JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
            
            Penjualan p = new Penjualan();
            
            if (userLogin != null) {
                p.setIdUser(userLogin.getIdUser());
            } else {
                p.setIdUser(1); 
            }
            
            p.setTotalHarga(total);
            p.setListDetail(keranjang);
            
            boolean sukses = penjualanDAO.simpanTransaksi(p);
            
            if (sukses) {
                JOptionPane.showMessageDialog(this, "Transaksi Berhasil Disimpan!");
                resetForm();
            } else {
                JOptionPane.showMessageDialog(this, "Transaksi Gagal!");
            }
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        if (keranjang.isEmpty()) {
            resetForm();
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, 
            "Yakin ingin membatalkan transaksi ini?\nSemua item di keranjang akan dihapus.", 
            "Konfirmasi Batal", 
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);
        
        if (confirm == JOptionPane.YES_OPTION) {
            resetForm(); 
        }
    }//GEN-LAST:event_btnBatalActionPerformed

    private void txtNamaProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaProdukActionPerformed

    private void txtJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahActionPerformed

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHargaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCariProduk;
    private javax.swing.JButton btnHapusItem;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblKeranjang;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtIdProduk;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtNamaProduk;
    // End of variables declaration//GEN-END:variables
}
